# Generated by Django 5.2.13 on 2026-04-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_user_account'),
        ('projects', '0002_seed_demo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='task',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('account', 'name')},
        ),
    ]
