# Generated by Django 5.2.13 on 2026-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_task_account_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='default_billable_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default billable rate for this task. NULL = use project/user rate.', max_digits=10, null=True),
        ),
    ]
