from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    AccountSettingsView,
    AddSampleDataView,
    InviteAcceptView,
    InviteAssignProjectsView,
    InviteCreateView,
    InviteResendView,
    InviteUpdateView,
    InviteValidateView,
    JobRoleViewSet,
    LoginView,
    MeAssignedPeopleView,
    MeAssignedProjectsView,
    MeNotificationsView,
    MeProfileView,
    MeView,
    MicrosoftSSOCallbackView,
    MicrosoftSSOStartView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    RefreshView,
    RegisterView,
    RemoveSampleDataView,
    UserDeleteView,
    UserDetailView,
    UserListView,
)

router = DefaultRouter()
router.register(r'job-roles', JobRoleViewSet, basename='job-role')

urlpatterns = [
    path('register/', RegisterView.as_view(), name='auth-register'),
    path('login/', LoginView.as_view(), name='auth-login'),
    path('microsoft/start/', MicrosoftSSOStartView.as_view(), name='auth-microsoft-start'),
    path('microsoft/callback/', MicrosoftSSOCallbackView.as_view(), name='auth-microsoft-callback'),
    path('token/refresh/', RefreshView.as_view(), name='auth-refresh'),
    path('me/', MeView.as_view(), name='auth-me'),
    path('me/profile/', MeProfileView.as_view(), name='auth-me-profile'),
    path('me/notifications/', MeNotificationsView.as_view(), name='auth-me-notifications'),
    path('me/assigned-people/', MeAssignedPeopleView.as_view(), name='auth-me-assigned-people'),
    path('me/assigned-projects/', MeAssignedProjectsView.as_view(), name='auth-me-assigned-projects'),
    path('account/settings/', AccountSettingsView.as_view(), name='account-settings'),
    path('account/remove-sample-data/', RemoveSampleDataView.as_view(), name='account-remove-sample-data'),
    path('account/add-sample-data/', AddSampleDataView.as_view(), name='account-add-sample-data'),
    path('users/', UserListView.as_view(), name='auth-users'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='auth-user-detail'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='auth-user-delete'),
    path('password-reset/', PasswordResetRequestView.as_view(), name='auth-password-reset'),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view(), name='auth-password-reset-confirm'),
    path('invites/', InviteCreateView.as_view(), name='auth-invite-create'),
    path('invites/validate/', InviteValidateView.as_view(), name='auth-invite-validate'),
    path('invites/accept/', InviteAcceptView.as_view(), name='auth-invite-accept'),
    path('invites/<int:pk>/resend/', InviteResendView.as_view(), name='auth-invite-resend'),
    path('invites/<int:pk>/', InviteUpdateView.as_view(), name='auth-invite-update'),
    path(
        'invites/<int:pk>/assign-projects/',
        InviteAssignProjectsView.as_view(),
        name='auth-invite-assign-projects',
    ),
    path('', include(router.urls)),
]
