# Generated by Django 5.2.13 on 2026-04-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='accounts.account')),
            ],
            options={
                'db_table': 'job_roles',
                'ordering': ['name'],
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='job_roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.jobrole'),
        ),
    ]
