# Generated by Django 5.2.13 on 2026-05-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_seed_sample_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_google_sso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='allow_microsoft_sso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='INR', max_length=8),
        ),
        migrations.AddField(
            model_name='account',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=12),
        ),
        migrations.AddField(
            model_name='account',
            name='default_capacity_hours',
            field=models.DecimalField(decimal_places=2, default=35, max_digits=5),
        ),
        migrations.AddField(
            model_name='account',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=dict, help_text='Per-module on/off flags, e.g. {"timesheet_approval": true, "reports": true}'),
        ),
        migrations.AddField(
            model_name='account',
            name='fiscal_year_start_month',
            field=models.IntegerField(default=1, help_text='1-12, month the fiscal year starts'),
        ),
        migrations.AddField(
            model_name='account',
            name='login_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='number_format',
            field=models.CharField(default='1,234.56', max_length=16),
        ),
        migrations.AddField(
            model_name='account',
            name='require_two_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='session_timeout_minutes',
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name='account',
            name='time_display',
            field=models.CharField(choices=[('hh_mm', 'HH:MM'), ('decimal', 'Decimal hours')], default='hh_mm', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='time_format',
            field=models.CharField(choices=[('12h', '12-hour clock'), ('24h', '24-hour clock')], default='12h', max_length=4),
        ),
        migrations.AddField(
            model_name='account',
            name='timer_mode',
            field=models.CharField(choices=[('duration', 'Track time via duration'), ('start_end', 'Track time via start and end time')], default='duration', max_length=12),
        ),
        migrations.AddField(
            model_name='account',
            name='timesheet_deadline',
            field=models.CharField(blank=True, default='', help_text='Free-form deadline like "Friday at 5:00pm". Used for reminders later.', max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='week_starts_on',
            field=models.CharField(choices=[('monday', 'Monday'), ('sunday', 'Sunday')], default='monday', max_length=10),
        ),
    ]
