# Generated by Django 5.2.13 on 2026-04-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('invoice_due_date_type', models.CharField(choices=[('custom', 'Custom'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('upon_receipt', 'Upon receipt')], default='custom', max_length=20)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['name'],
            },
        ),
    ]
