# Generated by Django 5.2.13 on 2026-05-01 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timesheets', '0002_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_account_email', models.EmailField(max_length=254)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('scope', models.TextField(blank=True, default='')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outlook_connections',
            },
        ),
        migrations.CreateModel(
            name='ImportedCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlook_event_id', models.CharField(max_length=512)),
                ('event_subject', models.CharField(blank=True, default='', max_length=512)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_from_outlook', to='timesheets.timeentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imported_calendar_events',
                'indexes': [models.Index(fields=['user', 'event_start'], name='imported_ca_user_id_39e003_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'outlook_event_id'), name='uniq_user_outlook_event')],
            },
        ),
    ]
