# Generated by Django 5.2.13 on 2026-05-05 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_employee_id_capacity'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=255, unique=True)),
                ('base_url', models.URLField(max_length=512)),
                ('product_type', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('shared_secret_encrypted', models.TextField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jira_connections', to='accounts.account')),
            ],
            options={
                'db_table': 'jira_connections',
                'indexes': [models.Index(fields=['account'], name='jira_connec_account_f27008_idx')],
            },
        ),
    ]
