# Generated by Django 5.2.13 on 2026-05-06 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_user_cost_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('time', 'Time'), ('profitability', 'Profitability'), ('detailed_time', 'Detailed Time'), ('activity', 'Activity Log')], max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_shared', models.BooleanField(default=False, help_text='When true, all admins/owners in the workspace can see this report.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='accounts.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_reports',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['account', 'owner'], name='saved_repor_account_1527c6_idx'), models.Index(fields=['account', 'kind'], name='saved_repor_account_4aabc2_idx')],
            },
        ),
    ]
