# Generated by Django 5.2.13 on 2026-05-05 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_employee_id_capacity'),
        ('projects', '0005_task_default_billable_rate'),
        ('timesheets', '0002_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='jira_issue_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['account', 'jira_issue_key'], name='time_entrie_account_7fe1ba_idx'),
        ),
    ]
