# Generated by Django 5.2.13 on 2026-05-07 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_allow_google_sso_account_allow_microsoft_sso_and_more'),
        ('timesheets', '0003_timeentry_jira_issue_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('time_entries', 'Time entries')], default='time_entries', max_length=32)),
                ('record_count', models.IntegerField(default=0)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='timeentry',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='timesheets.importbatch'),
        ),
    ]
